### ISSUE TITLE
No Such File or Directory OSError when running rnn.py?

### ISSUE THREAD

**Issue by double-u-d** [shariq/burgundy#3]
Hi @shariq, me & my team trying to get your code to run - however **rnn.py** keeps throwing errors to stdout in an endless loop
> OSError: [Errno 2] No such file or directory

directory structure:
![img_6321](https://cloud.githubusercontent.com/assets/10452470/26523536/6e7e55f6-4322-11e7-9570-a3e2d4dd32c6.jpg)

script output:
![img_6322](https://cloud.githubusercontent.com/assets/10452470/26523537/6eb95fd4-4322-11e7-9f71-da9e28b1a4c3.jpg)

Any tips on what could be the reason for that?

**Comment by shariq** [comment]
If you look at the comment at the top of rnn.py it says:
```
needs to be located in the same directory as
https://github.com/karpathy/char-rnn
follow instructions in the repo
```

Specifically it looks like that line is looking for a file named `train.lua` to be in the same directory as rnn.py, which it doesn't look like you have

Hope this helps :)
